{{- if .Values.istio.enabled -}}
# 开启了 istio 时使用 istio-service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    {{- include "scriptcat-list-frontend.istioSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scriptcat-list-frontend.istioSelectorLabels" . | nindent 4 }}
    scriptlist.frontend.io/environment: {{ .Values.istio.environment }}
{{- end }}