{{- if .Values.istio.enabled -}}
# 支持灰度发布,使用istio-gateway实现流量控制
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.nameOverride }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.hosts }}
        - {{ . | quote }}
        {{- end }}

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.nameOverride }}
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ .Values.nameOverride }}-gateway
  http:
    - match:
        {{- toYaml .Values.istio.canary.match | nindent 8 }}
      route:
        - destination:
            host: {{ .Values.nameOverride }}
            subset: canary
    - route:
        - destination:
            host: {{ .Values.nameOverride }}
            subset: prod

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.nameOverride }}
spec:
  host: {{ .Values.nameOverride }}
  subsets:
  - name: prod
    labels:
      {{- include "scriptcat-list-frontend.istioSelectorLabels" . | nindent 6 }}
      scriptlist.frontend.io/environment: prod
  - name: canary
    labels:
      {{- include "scriptcat-list-frontend.istioSelectorLabels" . | nindent 6 }}
      scriptlist.frontend.io/environment: canary

{{- end }}