{{- if not .Values.istio.enabled -}}
# 开启了 istio 时使用 istio-service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scriptcat-list-frontend.fullname" . }}
  labels:
    {{- include "scriptcat-list-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scriptcat-list-frontend.selectorLabels" . | nindent 4 }}

{{- end }}