variables:
  APP_NAME: "scriptlist-frontend"
  REPOSITORY: "scriptcat/list-frontend"

stages:
  - build
  - docker
  - deploy

build:
  stage: build
  image: node:16-alpine3.14
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ /^release\/.*$/ || $CI_COMMIT_BRANCH =~ /^test\/.*$/
  script:
    - npm ci
    - npm run build
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  artifacts:
    expire_in: 1 week
    paths:
      - build
      - public

build-docker:
  stage: docker
  image: docker:rc
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ /^release\/.*$/ || $CI_COMMIT_BRANCH =~ /^test\/.*$/
  variables:
    DOCKER_HOST: tcp://docker-dind:2375
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
      policy: pull
  before_script:
    - docker login $REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  script:
    - docker build . -f deploy/docker/Dockerfile -t $REGISTRY/$REPOSITORY:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY/$REPOSITORY:$CI_COMMIT_SHORT_SHA

deploy-pro:
  stage: deploy
  image: alpine/helm:3.9.0
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cd deploy/helm
    - |
      helm upgrade --install --namespace app $APP_NAME . -f values.yaml --kubeconfig $K3S_CONFIG \
      --set image.tag=$CI_COMMIT_SHORT_SHA --set image.repository=$REGISTRY/$REPOSITORY \
      --set env[1].value=$APP_API_PROXY

deploy-pre:
  stage: deploy
  image: alpine/helm:3.9.0
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\/.*$/
  script:
    - cd deploy/helm
    - |
      helm upgrade --install --namespace app $APP_NAME-pre . -f values.yaml --kubeconfig $K3S_CONFIG \
      --set image.tag=$CI_COMMIT_SHORT_SHA --set image.repository=$REGISTRY/$REPOSITORY \
      --set env[0].value=https://$PRE_DOMAIN/api/v2 \
      --set env[1].value=http://scriptlist-pre-cago.app.svc.cluster.local/api/v2 \
      --set env[2].value=5uk70yummcoe \
      --set ingress.hosts[0].host=$PRE_DOMAIN \
      --set ingress.tls[0].hosts[0]=$PRE_DOMAIN

deploy-test:
  stage: deploy
  image: alpine/helm:3.9.0
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^test\/.*$/
  script:
    - cd deploy/helm
    - |
      helm upgrade --install --namespace app $APP_NAME-test . -f values.yaml --kubeconfig $K3S_CONFIG \
      --set image.tag=$CI_COMMIT_SHORT_SHA --set image.repository=$REGISTRY/$REPOSITORY \
      --set env[0].value=https://$TEST_DOMAIN/api/v2 \
      --set env[1].value=http://scriptlist-test-cago.app.svc.cluster.local/api/v2 \
      --set env[2].value=sxIv1i8H1ZwnSAH \
      --set ingress.hosts[0].host=$TEST_DOMAIN \
      --set ingress.tls[0].hosts[0]=$TEST_DOMAIN
